### ISSUE TITLE
Output sprite sheets from .stitch assets

### ISSUE THREAD

**Issue by danschultz** [danschultz/stitch#7]
A .stitch asset contains the instructions to generate a sprite sheet. Having .stitch assets allows for some interesting possibilities:
- Developers can define a custom sprite sheet. Maybe with sprites coming from different folders or packages.
- Transformers from other packages can generate their own .stitch files to be transformed.

Stitch files are yaml files that contain the assets to include in the sprite sheet, and configuration options.

``` yaml
assets:
  - icons/info.png
  - icons/star.png
  - packages/social_icons/facebook.png
layout: grid
formats: all OR
  - css
  - sass
  - less
```
